### ISSUE TITLE
Error testing Linux Python2.7 wheels 

### ISSUE THREAD

**Issue by fbudin69500** [InsightSoftwareConsortium/ITKPythonPackage#129]
I get the following error message when creating the Python wheels for linux on my computer using the script [`dockcross-manylinux-build-wheels.sh`](https://github.com/InsightSoftwareConsortium/ITKPythonPackage/blob/master/scripts/dockcross-manylinux-build-wheels.sh). The error message is triggered inside [https://github.com/InsightSoftwareConsortium/ITKPythonPackage/blob/master/scripts/internal/manylinux-build-wheels.sh#L154]. It is easy to reproduce the bug by:
* Creating the wheel using the script mentioned above:
```
./scripts/dockcross-manylinux-build-wheels.sh cp27mu
```
* Connect to the docker container (`docker commit` to save the container, `docker run` with the saved container).
* Run the same Python commands from the docker container.

However, the wheels install correctly outside the docker container and the same test runs perfectly on my machine, outside of docker, when installing the packages that were just created in the docker container.

```
Looking in links: /work/dist
Collecting itk
Requirement already satisfied: numpy in /opt/_internal/cpython-2.7.15-ucs4/lib/python2.7/site-packages (from itk) (1.16.3)
Collecting itk-segmentation==5.0rc02.dev20190512 (from itk)
Collecting itk-core==5.0rc02.dev20190512 (from itk)
Collecting itk-filtering==5.0rc02.dev20190512 (from itk)
Collecting itk-numerics==5.0rc02.dev20190512 (from itk)
Collecting itk-io==5.0rc02.dev20190512 (from itk)
Collecting itk-registration==5.0rc02.dev20190512 (from itk)
Installing collected packages: itk-core, itk-numerics, itk-filtering, itk-segmentation, itk-io, itk-registration, itk
Successfully installed itk-5.0rc2.dev20190512 itk-core-5.0rc2.dev20190512 itk-filtering-5.0rc2.dev20190512 itk-io-5.0rc2.dev20190512 itk-numerics-5.0rc2.dev20190512 itk-registration-5.0rc2.dev20190512 itk-segmentation-5.0rc2.dev20190512
+ cd /home/francois.budin
+ /opt/python/cp27-cp27mu/bin/python -c 'from itk import ITKCommon;'
+ cd /home/francois.budin
+ /opt/python/cp27-cp27mu/bin/python -c 'import itk; image = itk.Image[itk.UC, 2].New()'
+ cd /home/francois.budin
+ /opt/python/cp27-cp27mu/bin/python -c 'import itkConfig; itkConfig.LazyLoading = False; import itk;'
+ cd /home/francois.budin
+ /opt/python/cp27-cp27mu/bin/python /work/scripts/internal/../../docs/code/testDriver.py
Traceback (most recent call last):
  File "ReadMedianWrite.py", line 11, in <module>
    itk.imwrite(median, output_filename)
  File "/home/francois.budin/.local/lib/python2.7/site-packages/itkExtras.py", line 515, in imwrite
    img.UpdateOutputInformation()
RuntimeError: /work/standalone-x64-build/ITKs/Modules/Core/Common/include/itkImageBase.hxx:333:
itk::ERROR: Image(0x4179df0): itk::ImageBase::CopyInformation() cannot cast PKN3itk10DataObjectE to PKN3itk9ImageBaseILj2EEE
Traceback (most recent call last):
  File "/work/scripts/internal/../../docs/code/testDriver.py", line 33, in <module>
    add_test(["ReadMedianWrite.py", baseline_image, output_image])
  File "/work/scripts/internal/../../docs/code/testDriver.py", line 10, in add_test
    subprocess.check_call(cmd)
  File "/opt/python/cp27-cp27mu/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/python/cp27-cp27mu/bin/python', 'ReadMedianWrite.py', '/tmp/tmpq4xu1Y/baseline.png', '/tmp/tmpq4xu1Y/filtered_image.png']' returned non-zero exit status 1
```

**Comment by thewtex** [comment]
We are Python 3 only, now :tada:
