### ISSUE TITLE
Windows failure for building remote module packages with v5.3rc04 Python wheels

### ISSUE THREAD

**Issue by tbirdso** [InsightSoftwareConsortium/ITKPythonPackage#189]
Error trace:
```
Traceback (most recent call last):
repairing D:\a\im\dist\itk_splitcomponents-2.0.6-cp37-cp37m-win_amd64.whl
  File "C:\Python37-x64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python37-x64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\P\IPP\venv-37-x64\Scripts\delvewheel.exe\__main__.py", line 7, in <module>
  File "C:\P\IPP\venv-37-x64\lib\site-packages\delvewheel\__main__.py", line 66, in main
    wr.repair(args.target, no_mangles, args.no_mangle_all, args.lib_sdir)
  File "C:\P\IPP\venv-37-x64\lib\site-packages\delvewheel\wheel_repair.py", line 436, in repair
    discovered, ignored = patch_dll.get_all_needed(extension_module_path, self._no_dlls, self._wheel_dirs)[:2]
  File "C:\P\IPP\venv-37-x64\lib\site-packages\delvewheel\patch_dll.py", line 272, in get_all_needed
    dll_path = find_library(dll_name, wheel_dirs, lib_bitness)
  File "C:\P\IPP\venv-37-x64\lib\site-packages\delvewheel\patch_dll.py", line 159, in find_library
    contents = os.listdir(directory)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '"C:\\P\\grep'
finding DLL dependencies
Traceback (most recent call last):
  File "C:\P\IPP\scripts\windows_build_module_wheels.py", line 142, in <module>
    fixup_wheels(args.py_envs, ';'.join(args.lib_paths), ';'.join(args.exclude_libs))
  File "C:\P\IPP\scripts\windows_build_module_wheels.py", line 129, in fixup_wheels
    fixup_wheel(py_envs, wheel, lib_paths, exclude_libs)
  File "C:\P\IPP\scripts\windows_build_module_wheels.py", line 119, in fixup_wheel
    os.path.join(ROOT_DIR, "dist"), filepath])
  File "C:\Python37-x64\lib\subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:/P/IPP\\venv-37-x64\\Scripts\\delvewheel.exe', 'repair', '--no-mangle-all', '--add-path', 'C:/P/IPP/oneTBB-prefix/bin', '--no-dll', '', '--ignore-in-wheel', '-w', 'D:\\a\\im\\dist', 'D:\\a\\im\\dist\\itk_splitcomponents-2.0.6-cp37-cp37m-win_amd64.whl']' returned non-zero exit status 1.
SCRIPT_DIR: C:\P\IPP\scripts
ROOT_DIR: D:\a\im
```

Still investigating the root issue as `grep` appears to be extracted properly during setup:
```
2022-04-07T19:58:45.7694108Z [36;1mcurl -L "https://data.kitware.com/api/v1/file/5bbf87ba8d777f06b91f27d6/download/grep-win.zip" -o "grep-win.zip"[0m
2022-04-07T19:58:45.7694565Z [36;1m7z x grep-win.zip -o/c/P/grep -aoa -r[0m
...
2022-04-07T20:04:01.4469693Z Extracting archive: grep-win.zip
2022-04-07T20:04:01.4646087Z --
2022-04-07T20:04:01.4646730Z Path = grep-win.zip
2022-04-07T20:04:01.4647189Z Type = zip
2022-04-07T20:04:01.4647533Z Physical Size = 917114
2022-04-07T20:04:01.4648346Z 
2022-04-07T20:04:01.4648698Z Everything is Ok
2022-04-07T20:04:01.4648967Z 
2022-04-07T20:04:01.4649167Z Files: 6
2022-04-07T20:04:01.4649496Z Size:       1397864
2022-04-07T20:04:01.4649836Z Compressed: 917114
```

[ITKSplitComponents failure](https://github.com/InsightSoftwareConsortium/ITKSplitComponents/runs/5875069162?check_suite_focus=true)

**Comment by tbirdso** [comment]
@thewtex FYI there is also an issue building v5.3rc04 external module wheels for Windows, please see description

**Comment by tbirdso** [comment]
Verified using tmate SSH client that "C:\\P\\grep" is a valid directory on Windows ITK Python runner. It looks like a string may be malformed, was able to recreate the error by adding an extra quotation in the path. I.e, "C:\\\\P\\\\grep vs C:\\\\P\\\\grep.

```
removing _skbuild\win-amd64-3.7\setuptools\bdist.win-amd64\wheel
C:\P\IPP\venv-37-x64\lib\site-packages\setuptools\command\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
C:\P\IPP\venv-37-x64\lib\site-packages\wheel\bdist_wheel.py:82: RuntimeWarning: Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
  warn=(impl == 'cp')):
C:\P\IPP\venv-37-x64\lib\site-packages\wheel\bdist_wheel.py:87: RuntimeWarning: Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
  sys.version_info < (3, 8))) \
Traceback (most recent call last):
repairing D:\a\im\dist\itk_splitcomponents-2.0.6-cp37-cp37m-win_amd64.whl
  File "C:\Python37-x64\lib\runpy.py", line 193, in _run_module_as_main
finding DLL dependencies
    "__main__", mod_spec)
  File "C:\Python37-x64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\P\IPP\venv-37-x64\Scripts\delvewheel.exe\__main__.py", line 7, in <module>
  File "C:\P\IPP\venv-37-x64\lib\site-packages\delvewheel\__main__.py", line 66, in main
    wr.repair(args.target, no_mangles, args.no_mangle_all, args.lib_sdir)
  File "C:\P\IPP\venv-37-x64\lib\site-packages\delvewheel\wheel_repair.py", line 436, in repair
    discovered, ignored = patch_dll.get_all_needed(extension_module_path, self._no_dlls, self._wheel_dirs)[:2]
  File "C:\P\IPP\venv-37-x64\lib\site-packages\delvewheel\patch_dll.py", line 272, in get_all_needed
    dll_path = find_library(dll_name, wheel_dirs, lib_bitness)
  File "C:\P\IPP\venv-37-x64\lib\site-packages\delvewheel\patch_dll.py", line 159, in find_library
    contents = os.listdir(directory)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '"C:\\P\\grep'
SCRIPT_DIR: C:\P\IPP\scripts
ROOT_DIR: D:\a\im
```

**Comment by tbirdso** [comment]
Investigating `delvewheel/path_dll.py`, it looks like [find_library](https://github.com/adang1345/delvewheel/blob/master/delvewheel/patch_dll.py#L156-L159) is simply iterating over PATH contents and finding directory contents, so perhaps the `grep` directory is set incorrectly? However, the last change to where we add `grep` to PATH was 4 years ago in [https://github.com/InsightSoftwareConsortium/ITKPythonPackage/blame/master/scripts/windows-download-cache-and-build-module-wheels.ps1](https://github.com/InsightSoftwareConsortium/ITKPythonPackage/blame/master/scripts/windows-download-cache-and-build-module-wheels.ps1).

**Comment by tbirdso** [comment]
Aha, the issue was in the external module CI procedure where extra quotes were added to PATH. Most likely this conflicted somehow with recent updates to how we use delvewheel. I will keep an eye out for this issue as we bump external modules for rc04.

**Comment by tbirdso** [comment]
See ITKSplitComponents fix example at [https://github.com/InsightSoftwareConsortium/ITKSplitComponents/pull/51](https://github.com/InsightSoftwareConsortium/ITKSplitComponents/pull/51)
