### ISSUE TITLE
WrapITKBuildOptionsPython is not found when importing itk with LazyLoading disabled

### ISSUE THREAD

**Issue by jcfr** [InsightSoftwareConsortium/ITKPythonPackage#2]
```
>>> itkConfig.LazyLoading = False
>>> import itk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jcfr/.virtualenvs/test0itk/local/lib/python2.7/site-packages/itk/__init__.py", line 65, in <module>
    itkBase.LoadModule(module, thisModule.__dict__)
  File "/home/jcfr/.virtualenvs/test0itk/local/lib/python2.7/site-packages/itkBase.py", line 128, in LoadModule
    module = loader.load(swigModuleName)
  File "/home/jcfr/.virtualenvs/test0itk/local/lib/python2.7/site-packages/itkBase.py", line 249, in load
    fp, pathname, description = imp.find_module(name)
ImportError: No module named WrapITKBuildOptionsPython

```

**Comment by jcfr** [comment]
This will be fixed by https://github.com/scikit-build/scikit-build/pull/245

**Comment by thewtex** [comment]
Nice!
