### ISSUE TITLE
delocate is failing on Python files

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITKPythonPackage#78]
Interestingly, `delocate-listdeps` has recently [started to fail](https://travis-ci.org/InsightSoftwareConsortium/ITKRingArtifact/builds/309055362) when building module packages:

```
+/Users/Kitware/Dashboards/ITK/ITKPythonPackage/scripts/../venvs/2.7/bin/delocate-listdeps /Users/travis/build/InsightSoftwareConsortium/ITKRingArtifact/dist/itk_ringartifact-0.1.0-cp27-cp27m-macosx_10_6_x86_64.whl /Users/travis/build/InsightSoftwareConsortium/ITKRingArtifact/dist/itk_ringartifact-0.1.0-cp34-cp34m-macosx_10_6_x86_64.whl /Users/travis/build/InsightSoftwareConsortium/ITKRingArtifact/dist/itk_ringartifact-0.1.0-cp35-cp35m-macosx_10_6_x86_64.whl /Users/travis/build/InsightSoftwareConsortium/ITKRingArtifact/dist/itk_ringartifact-0.1.0-cp36-cp36m-macosx_10_6_x86_64.whl
/Users/travis/build/InsightSoftwareConsortium/ITKRingArtifact/dist/itk_ringartifact-0.1.0-cp27-cp27m-macosx_10_6_x86_64.whl:
Traceback (most recent call last):
  File "/Users/Kitware/Dashboards/ITK/ITKPythonPackage/scripts/../venvs/2.7/bin/delocate-listdeps", line 61, in <module>
    main()
  File "/Users/Kitware/Dashboards/ITK/ITKPythonPackage/scripts/../venvs/2.7/bin/delocate-listdeps", line 44, in main
    lib_dict = wheel_libs(path)
  File "/Users/kitware/Dashboards/ITK/ITKPythonPackage/venvs/2.7/lib/python2.7/site-packages/delocate/libsana.py", line 161, in wheel_libs
    lib_dict = tree_libs(tmpdir, filt_func)
  File "/Users/kitware/Dashboards/ITK/ITKPythonPackage/venvs/2.7/lib/python2.7/site-packages/delocate/libsana.py", line 54, in tree_libs
    for install_name in get_install_names(depending_libpath):
  File "/Users/kitware/Dashboards/ITK/ITKPythonPackage/venvs/2.7/lib/python2.7/site-packages/delocate/tools.py", line 173, in get_install_names
    if not _line0_says_object(lines[0], filename):
  File "/Users/kitware/Dashboards/ITK/ITKPythonPackage/venvs/2.7/lib/python2.7/site-packages/delocate/tools.py", line 143, in _line0_says_object
    raise InstallNameError('Unexpected first line: ' + line0)
delocate.tools.InstallNameError: Unexpected first line: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: '/private/var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/tmp_NF5m6/itk/itkFourierStripeArtifactImageFilterPython.py': The file was not recognized as a valid object file
```

CC: @jcfr @matthew-brett

**Comment by jcfr** [comment]
The corresponding delocated code is https://github.com/matthew-brett/delocate/blob/aa323245fba373e307128ef227385241fde70160/delocate/tools.py#L133-L180

Could you report the output of `otool -L` for ringartifact python module ?

**Comment by jcfr** [comment]
This is strange, the following message:

```
'/private/var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/tmp_NF5m6/itk/itkFourierStripeArtifactImageFilterPython.py': The file was not recognized as a valid object file
```
 should have been recognized as an exception and ignored.

See https://github.com/matthew-brett/delocate/blob/aa323245fba373e307128ef227385241fde70160/delocate/tools.py#L138-L139

```
    if ("'%s': The file was not recognized as a valid object file" % filename) in line0:
        return False
```

**Comment by thewtex** [comment]
It may be an otool version issue. I could not reproduce the error locally.

Locally, I have

```
$ otool --version
llvm-otool(1): Apple Inc. version cctools-895
Apple LLVM version 8.0.0 (clang-800.0.42.1)
```

TravisCI
```
$ otool --version
llvm-otool(1): Apple Inc. version cctools-898
Apple LLVM version 8.1.0 (clang-802.0.42)
```

I am working on getting the output of `otool -L` on TravisCI...

**Comment by jcfr** [comment]
You could also remote connect to travis. See http://scikit-ci-addons.readthedocs.io/en/latest/addons.html#enable-worker-remote-access-sh

It is not a first class terminal .. but it should allow to get the output of otool

**Comment by thewtex** [comment]
> See http://scikit-ci-addons.readthedocs.io/en/latest/addons.html#enable-worker-remote-access-sh

Neat!

**Comment by thewtex** [comment]
Maybe related to the XCode 8.3 update?:
  https://blog.travis-ci.com/2017-11-21-xcode8-3-default-image-announce

**Comment by matthew-brett** [comment]
Yes probably, I guess the error text has changed in some subtle way... I'll adapt the code to whatever it is - any clues?

**Comment by thewtex** [comment]
Nothing is popping out. Here is the output on TravisCI:

```
0.03s$ otool -L ./itkFourierStripeArtifactImageFilterPython.py
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: './itkFourierStripeArtifactImageFilterPython.py': The file was not recognized as a valid object file
```

Here is the output locally:

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: '/Users/kitware/Dashboards/matt/ITKRingArtifact/dist/itk_ringartifact-0.1.0-cp27-cp27m-macosx_10_6_x86_64/itkFourierStripeArtifactImageFilterPython.py': The file was not recognized as a valid object file.
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: internal objdump command failed
```

**Comment by matthew-brett** [comment]
It does look the `otool` output changed for the newest version.  I've put up a set of fixes at https://github.com/matthew-brett/delocate/pull/27 - any takers for a quick review?

**Comment by thewtex** [comment]
Thanks, @matthew-brett LGTM
